### ISSUE TITLE
Error with broadcasting in ResNet18

### ISSUE THREAD

**Issue by system123** [broadinstitute/keras-resnet#21]
My input data size is (112, 112, 1), but I receive this error when trying to run the Resnet18 model on my data. 

```
Traceback (most recent call last):
  File "/src/sar_optical_matching.py", line 183, in <module>
    if __name__=="__main__": main()
  File "/src/sar_optical_matching.py", line 146, in main
    model = model_def.build(input_shape, verbose=args.verbose, one_hot=args.one_hot)
  File "/src/models/resnet_siamese.py", line 21, in build
    y_opt = keras_resnet.models.ResNet18(x_opt)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras_resnet/models.py", line 103, in __init__
    super(ResNet18, self).__init__(inputs, [2, 2, 2, 2], block)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras_resnet/models.py", line 61, in __init__
    x = block(features, strides, j == 0 and k == 0)(x)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras_resnet/block/__init__.py", line 48, in f
    y = _shortcut(x, y)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras_resnet/block/__init__.py", line 121, in _shortcut
    return keras.layers.add([a, b])
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras/layers/merge.py", line 455, in add
    return Add(**kwargs)(inputs)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras/engine/topology.py", line 560, in __call__
    self.build(input_shapes)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras/layers/merge.py", line 84, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "/opt/conda/envs/custom/lib/python3.6/site-packages/keras/layers/merge.py", line 55, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (7, 7, 512) (4, 4, 512)
```

**Comment by mcquin** [comment]
Similar error. ResNet50 with input shape (48, 48, 3):

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-4047d9db4a9c> in <module>()
      1 x = keras.layers.Input(shape)
      2 
----> 3 y = keras_resnet.ResNet50(x)
      4 
      5 y = keras.layers.Flatten()(y.output)

/home/mcquin/.local/lib/python3.6/site-packages/keras_resnet/models.py in __init__(self, inputs)
    145         block = keras_resnet.block.bottleneck
    146 
--> 147         super(ResNet50, self).__init__(inputs, [3, 4, 6, 3], block)
    148 
    149 

/home/mcquin/.local/lib/python3.6/site-packages/keras_resnet/models.py in __init__(self, inputs, blocks, block)
     59                     strides = (1, 1)
     60 
---> 61                 x = block(features, strides, j == 0 and k == 0)(x)
     62 
     63             features *= 2

/home/mcquin/.local/lib/python3.6/site-packages/keras_resnet/block/__init__.py in f(x)
     90 
     91         y = keras.layers.BatchNormalization(axis=axis)(y)
---> 92         y = _shortcut(x, y)
     93         y = keras.layers.Activation("relu")(y)
     94 

/home/mcquin/.local/lib/python3.6/site-packages/keras_resnet/block/__init__.py in _shortcut(a, b)
    119             a = keras.layers.BatchNormalization(axis=1)(a)
    120 
--> 121     return keras.layers.add([a, b])

/home/mcquin/.local/lib/python3.6/site-packages/keras/layers/merge.py in add(inputs, **kwargs)
    453         A tensor, the sum of the inputs.
    454     """
--> 455     return Add(**kwargs)(inputs)
    456 
    457 

/home/mcquin/.local/lib/python3.6/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    569                     self.build(input_shapes[0])
    570                 else:
--> 571                     self.build(input_shapes)
    572                 self.built = True
    573 

/home/mcquin/.local/lib/python3.6/site-packages/keras/layers/merge.py in build(self, input_shape)
     82             else:
     83                 shape = input_shape[i][1:]
---> 84             output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
     85         # If the inputs have different ranks, we have to reshape them
     86         # to make them broadcastable.

/home/mcquin/.local/lib/python3.6/site-packages/keras/layers/merge.py in _compute_elemwise_op_output_shape(self, shape1, shape2)
     53                     raise ValueError('Operands could not be broadcast '
     54                                      'together with shapes ' +
---> 55                                      str(shape1) + ' ' + str(shape2))
     56                 output_shape.append(i)
     57         return tuple(output_shape)

ValueError: Operands could not be broadcast together with shapes (3, 3, 2048) (2, 2, 2048)
```

**Comment by mcquin** [comment]
Installed versions:

```
keras-resnet==0.0.4
Keras==2.0.6
tensorflow-gpu==1.1.0
Theano==0.9.0
```

**Comment by 0x00b1** [comment]
Thanks, @system123 and @mcquin! Looking into this.

**Comment by 0x00b1** [comment]
Fixed! You can either upgrade from source or wait a few minutes until the new release is available on PyPI. :D

```Python
pip install --upgrade keras-resnet
```

**Comment by system123** [comment]
Great thanks :)

**Comment by mcquin** [comment]
💖 💖 💖 💖 💖
